name: CI Pipeline

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Pegar código do repositório"
        uses: actions/checkout@v3

      - name: "Configurar python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: "Instalar dependências"
        run: |
          pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt

      - name: "Verificar compilação"
        run: |
          python3 -m py_compile $(find . -name "*.py")
